#!/usr/bin/env node
var visitors = require("react-tools/vendor/fbtransform/visitors");
var jstransform = require('jstransform');


process.stdin.resume();
process.stdin.setEncoding("utf-8");

var js = "";
process.stdin.on("data", function(data) {
    js += data;
});

process.stdin.on("end", function() {
    var visitorList = visitors.getAllVisitors();
    js = jstransform.transform(visitorList, js).code;

    process.stdout.write(js);
});
